name: neo_cli
description: Neo CLI.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.1

executables:
  neo: neo_cli

dependencies:
  args: ^2.6.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
