name: neo_cli
description: The Neo CLI. Your gateway to experiencing Flutter app development with exceptional speed and precision thanks to the Neo framework.
version: 0.3.1

environment:
  sdk: ^3.6.1

executables:
  neo: neo_cli

dependencies:
  args: ^2.6.0
  path: ^1.8.0
  glob: ^2.1.2
  build: ^2.4.1
  yaml: ^3.1.2
  yaml_edit: ^2.2.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.4.8
  source_gen: ^2.0.0
  analyzer: ^7.3.0
